services:
  app:
    build: 
      context: .
      target: development
      args:
        - UID=${UID}
        - GID=${UID}
    volumes:
      - .:/app
      - gem_cache:/gems
    env_file:
      - .env
        
volumes:
  gem_cache:
